export const GUN_CONFIG = {
    ar: {
        displayName: 'Assault Rifle',
        damage: 18,
        fireRate: 150,
        bulletSpeed: 600,
        bulletLifetime: 1200,
        magazineSize: 30,
        ammoType: 'rifle',
        spread: 0.05,
        pellets: 1,
        isRocket: false,
        aoeRadius: 0,
        aoeDamage: 0,
    },
    sniper: {
        displayName: 'Sniper Rifle',
        damage: 95,
        fireRate: 1500,
        bulletSpeed: 1200,
        bulletLifetime: 2500,
        magazineSize: 5,
        ammoType: 'sniper',
        spread: 0,
        pellets: 1,
        isRocket: false,
        aoeRadius: 0,
        aoeDamage: 0,
    },
    shotgun: {
        displayName: 'Shotgun',
        damage: 14,
        fireRate: 700,
        bulletSpeed: 400,
        bulletLifetime: 400,
        magazineSize: 12,
        ammoType: 'shells',
        spread: 0.18,
        pellets: 7,
        isRocket: false,
        aoeRadius: 0,
        aoeDamage: 0,
    },
    rocket: {
        displayName: 'Rocket Launcher',
        damage: 80,
        fireRate: 2000,
        bulletSpeed: 200,
        bulletLifetime: 5000,
        magazineSize: 4,
        ammoType: 'rockets',
        spread: 0,
        pellets: 1,
        isRocket: true,
        aoeRadius: 96,
        aoeDamage: 40,
    },
    minigun: {
        displayName: 'Minigun',
        damage: 10,
        fireRate: 80,
        bulletSpeed: 500,
        bulletLifetime: 900,
        magazineSize: 150,
        ammoType: 'rifle',
        spread: 0.12,
        pellets: 1,
        isRocket: false,
        aoeRadius: 0,
        aoeDamage: 0,
    },
};

// Ammo pack drop amounts per type
export const AMMO_PACK_AMOUNTS = {
    rifle: 30,
    sniper: 5,
    shells: 10,
    rockets: 3,
};
